### PR TITLE
Show panel error on manifest/item label navigation when failing to find manifest/item

### LINKED ISSUE #820: Bug: Navigating to a new item produces not so human-friendly error message
**Describe the bug**

**To Reproduce**
1. Go to 'https://textapi.dev.vierwachen.d.sub.uni-goettingen.de/api/4w/reproduction/collection.json'
2. Navigate in Item Label by selecting 280

**Actual behaviour**
Following error is shown

Image

**Expected behavior**
A more human readable error message should be displayed

**Additional context**
Manifest id in 'Collection Sequence Object' and in manifest object does not coincide. Following is screenshot

Image

### PR DESCRIPTION
**Pull request by orlinmalkja**
Closes #820

### CODE REVIEW

File: src/contexts/PanelContext.tsx [hunk 1]
```diff
@@ -108,6 +108,16 @@ const PanelProvider: FC<PanelProviderProps> = ({ children, panelId }) => {
...
+        showBoundary(new CustomError(t('panel_init_error'), t('manifest_not_found')))
+        return
+      }
+
+      if (config.itemIndex === -1) {
+        showBoundary(new CustomError(t('panel_init_error'), t('item_not_found')))
+        return
+      }
+
       const manifestUrl = collection.sequence[config.manifestIndex ?? 0].id
```
Comment (orlinmalkja) [inline src/contexts/PanelContext.tsx]: this line checks for nullish values (null or NaN) - i.e when manifestIndex or itemIndex are not provided at all in config. 
We would miss this error of not providing coinciding manifest ids in 'collection sequence object' and the 'manifest' object
