### PR TITLE
Check for witness value in witness chip

### LINKED ISSUE #770: Bug: Not found witness causes error
**Describe the bug**
A not found witness causes an error

**To Reproduce**
1. Navigate to London Brit. 7200, Item 114v
2. Switch to transcription content
3. Open annotations panel
4. Navigate to next item

 **Actual behavior**
TIDO crashes

**Expected behavior**
To navigate in new item AND load correctly the witnesses

**Additional context**

### PR DESCRIPTION
**Pull request by orlinmalkja**
Closes #770

### CODE REVIEW

File: src/components/panel/annotations/WitnessChip.tsx [hunk 1]
```diff
@@ -10,16 +10,16 @@ const WitnessChip: FC<Props> = React.memo(({ idno }) => {
   const { witnesses } = usePanel()
 
   function getWitnessLabel(idno: string) {
-    return witnesses.find(w => w.idno === idno).idnoAlt ?? 'none'
+    return witnesses.find(w => w.idno === idno)?.idnoAlt ?? 'none'
```
Comment (paulpestov) [inline src/components/panel/annotations/WitnessChip.tsx:13]: i think we have a translation for "unknown", maybe it fits here
