### PR TITLE
Tree fixes

### LINKED ISSUE #613: Tree Selection popup should close on click outside
**Describe the bug**
see title

**To Reproduce**
1. Open global tree
2. Expand to item level
3. Click on item
4. Click some other tree node

**Actual behavior**
The selection popup stays visible

**Expected behavior**
It should disappear, unless I click another item

### PR DESCRIPTION
**Pull request by orlinmalkja**
Closes #613, #614

### CODE REVIEW

File: src/components/tree/GlobalTree.tsx [hunk 1]
```diff
@@ -25,17 +29,33 @@ const GlobalTree: FC = () => {
...
-    { showSelectionModal && <div
-      className="t-fixed t-z-50 t-p-2 t-bg-white t-border t-border-gray-200 t-shadow-md t-rounded"
-      style={{
-        top: `${selectedPosition?.y + 40}px`,
-        left: `${selectedPosition?.x}px`,
-      }}
-    >
-      <GlobalTreeSelectionModalContent selectedItemIndices={selectedItemIndices.current} onSelect={() => setShowSelectionModal(false)} />
-    </div> }
+    <TreeProvider onSelect={onSelectNode} getChildren={getChildren}>
```
Comment (orlinmalkja) [inline src/components/tree/GlobalTree.tsx:46]: I wrap both the 'Tree' and 'GlobalTreeSelectionModalContent' under the same provider so that they can have synchronous access on the TreeContextProvider variables/methods, namely: setSelectedNodeId and selectedNodeId.

File: src/components/tree/Tree.tsx [hunk 2]
```diff
@@ -1,17 +1,12 @@
 import { FC } from 'react'
 
-
-import { TreeProvider } from '@/contexts/TreeContext.tsx'
-
 import TreeNode from '@/components/tree/TreeNode'
 
 interface TreeProps {
-  nodes: TreeNode[],
-  onSelect(node: TreeNode, target: HTMLElement): void,
```
Comment (orlinmalkja) [inline src/components/tree/Tree.tsx:10]: I realised that 'onSelect' and 'getChildren' are not needed in Tree, but in TreeNode.

**Review by paulpestov — APPROVED** [review]
